[package]
name = "udi_forwarder"
version = "0.1.0"
authors = ["Dan McNulty <dkmcnulty@gmail.com>"]

[lib]
name = "udi_forwarder"
path = "src/lib.rs"

[[bin]]
name = "udi-forwarder"
path = "src/bin.rs"

[dependencies]

mio = "^0.5.0"
notify = "^2.6.1"
ws = "^0.5.3"
log = "0.3.6"
log4rs = "0.5.0"
